### ISSUE TITLE
Unable to locate startup.nsh

### ISSUE THREAD

**Issue by ganakee** [alexhorner/WD-DX4000-Installer#6]
Thank you for this great app.

I used the precompiled ISO images ([https://github.com/alexhorner/WD-DX4000-Installer](https://github.com/alexhorner/WD-DX4000-Installer)) to do a solderless install of Debian Buster. I installed to a separate USB drive plugged into the DX4000. The install took about an hour.

The installer instructions indicate that after installing, the DX4000 will not boot until startup.nsh is copied. The instructions here (respectfully) are vague. 

1) startup.nsh did not appear in my installer copy anywhere. 
2) It is unclear how to discover and mount the BOOT drive (not the install partition).

2) I shutdown the DX4000. I seperately downloaded the startup.sh for BUSTER at https://github.com/alexhorner/WD-DX4000-Installer/tree/master/Bullseye and saved to my local drive.
3) I removed the USB drive from the DX4000 and inserted into my Linux system. I used gparted to find and mount the BOOT partition (NOT the install partition--if you see a plethora of directories such as bin home usr etc. you mounted the wrong partition). The BOOT partition had only an EFI directory.
4) I copied the separately downloaded startup.nsh to the root of the BOOT partition.
4.5) I used ls -la to verify ownership as root root.
5) I unmounted the BOOT, removed the USB drive, inserted the USB into the DX4000 and booted. Now the DX4000 booted.

I might have been able to mount the USB with the installer. But lsblk did not show all the partitions or drives even after disk-detect.

**Comment by alexhorner** [comment]
Hi @ganakee 

The installation instructions are intentionally vague at the moment. This is a prerelease which does not mount and finish the final startup.nsh step for you.

There is an expectation that there is some familiarity with Linux and being able to mount the appropriate partition (after the disk-detect) is included in that expectation. This is usually the first partition of the connected disk, and it is also possible to use trial and error mounting various partitions until you correctly identify the appropriate partition to copy the file to.

You can also easily see which disk is not the correct one by using the `df -h` command which lists which disk is mounted as `/media` which is the installer disk.

I would also like to point out the Buster ISO is now outdated and may not fully match the instructions. The instructions will always match the latest available ISO, which is currently Bullseye.

I have checked the Bullseye ISO, and I can confirm from the installer shell the startup.nsh file is located at `/startup.nsh`
![image](https://user-images.githubusercontent.com/33007665/202920134-b0c65a71-5bb3-4d6a-8132-b30cd326861a.png)

You say

> BUSTER

but you then link to the Bullseye file tree, so I am not sure which you actually mean. Regardless, they are identical, so it does not matter.

The steps you followed from your external system in order to mount the boot partition and insert the startup.nsh is an alternative approach (and in my opinion, more complex, hence I did not document it) and it appears it worked perfectly for you, for which I am glad.

I will reply again soon after a test installation, in which I will verify whether an externally connected USB disk will be detected by the installer.

It appears you might have resolved your issue now? If not, or if you have any further questions regarding this specific issue, please let me know, otherwise please close the issue. Also, feel free to open a discussion at the top of the repository if you would like to have a casual chat regarding the installer in general, I'm always open to suggestions and constructuve criticism!

**Comment by alexhorner** [comment]
I have confirmed that USB disks are detected correctly as the second stage after disk-detect

**Comment by ganakee** [comment]
This is a GREAT app and thank you for your work on it. Did not mean to offend with the vagueness.


I was able to get everything working and the DX4000 is now running Bullseye. I am working through the fans and LCD tutorials as I write.

Thanks again for the reply. Yes, my work-around was complex. I am not sure why my ISO does not show the startup.nsh file. I re-flashed the ISO for the installer (BULLSEYE) and I still do not see any startup.nsh files. 

Got it running with your great work!

IF IT HELPS: The output of `ls > bullseye.txt` on the installer USB =
```
addrk.cfg
adtxt.cfg
boot
boot.cat
drk.cfg
drkmenu.cfg
EFI
exithelp.cfg
f10.txt
f1.txt
f2.txt
f3.txt
f4.txt
f5.txt
f6.txt
f7.txt
f8.txt
f9.txt
g2ldr
g2ldr.mbr
initrd.gz
isolinux.bin
isolinux.cfg
ldlinux.c32
libcom32.c32
libutil.c32
linux
menu.cfg
prompt.cfg
rqdrk.cfg
rqtxt.cfg
setup.exe
splash.png
stdmenu.cfg
txt.cfg
vesamenu.c32
win32-loader.ini
```

**Comment by alexhorner** [comment]
Hi @ganakee

No offense taken at all, I'm just setting expectations.

You will not find the startup.nsh on the root of the ISO. You will only find it on the root of the running installer, as shown in my screenshot. It is embedded deeper in the ISO and is only directly accessible from the installer shell, hence you must start the installer shell and use it to copy the file to the boot partition.

Best of luck with the fan and LCD tutorials!

**Comment by alexhorner** [comment]
~~Hit the wrong button, oopsie! Close when you feel is appropriate~~

**Comment by ganakee** [comment]
Great. Fans working and LCD underway.The driver was missiing from lcdproc hd

**Comment by alexhorner** [comment]
> Great. Fans working and LCD underway.The driver was missiing from lcdproc hd

Interesting! I'll investigate this soon

**Comment by ganakee** [comment]
Thanks. I don't want to open a new can-of-worms. 

From what I can tell (I am not at that machine), I installed lcdproc as directed. The install went fine.

I modified the config files as specified in the instructions.
The LCD on boot dims but then never displays lcdproc.

When I run sudo systemctl status lcdproc, systemctl reports an error and failure to load with indicating the hd44780.so driver is missing. /etc/lib/x86.../lcdproc does not have a hd44780.so file.

I tried copying an hd44780.so from another distro to the correct place but the driver still does not load--systemctl restart lcdproc etc. I also ran systemctl reload-daemon as well. It definitely looks like hd44780.so is missing. I did a quick web search and others seem to suggest a similar issue.

If I run the direct command to adjust brightness (echo ....) the LCD dims. But nothing else works for the LCD with lcdproc.

No big issue. Just FYI. Fans seem to work.

**Comment by alexhorner** [comment]
Hi @ganakee 

I consider this a big issue, so if you want to open a new issue on the repo go ahead. I will investigate it anyway though.

Thanks

**Comment by ganakee** [comment]
OK. I can open a new item. But I figured this out today. If this helps....

For some reason, when installing lcdproc the installation failed to install lcdproc-extra-drivers. The lcdproc install goes fine and lists lcdproc-extra-drivers but does did not install it. I did not know this.

Last night, I searched and verified what needs to be installed for lcdproc. I checked each main package and saw that lcdproc-extra-drivers contains the hd44780.so driver.

Today, I manually installed lcdproc-extra-drivers and rebooted. Now the LCD screen works just as you describe.

I did not try to replicate the install error. But the issue arose for me from just using `sudo apt install lcdproc` alone. I needed to manually also install `sudo apt install lcdproc-extra-drivers` to get the hd44780.so driver so the LCD works.

**Comment by alexhorner** [comment]
> OK. I can open a new item. But I figured this out today. If this helps....
> 
> For some reason, when installing lcdproc the installation failed to install lcdproc-extra-drivers. Package lcdproc-extra-drivers contains the hd44780 driver. The lcdproc install goes fine and lists lcdproc-extra-drivers as being installed but did not install it for me. I did not know this.
> 
> Last night, I searched and verified what needs to be installed for lcdproc. I checked each main package and saw that lcdproc-extra-drivers contains the hd44780.so driver.
> 
> Today, I manually installed lcdproc-extra-drivers and rebooted. Now the LCD screen works just as you describe.
> 
> I did not try to replicate the install error. But the issue arose for me from just using `sudo apt install lcdproc` alone. I needed to manually also install `sudo apt install lcdproc-extra-drivers` to get the hd44780.so driver so the LCD works.
> 
> List of [lcdproc package for Debian](https://packages.debian.org/source/bullseye/lcdproc) noting the build includes lcdproc-extra-drivers, source code contains the driver build files.
> 
> List of [lcdproc-extra-drivers in Debian](https://packages.debian.org/bullseye/amd64/lcdproc-extra-drivers/filelist)

I have attempted to replicate this issue twice with fresh installs from the Bullseye ISO, and I have not succeeded. I believe you probably just ran into an interruption whilst installing lcdproc leading to a partial install. Maybe run the install for lcdproc again too to make sure you got everything?

**Comment by ganakee** [comment]
Thanks again. The DX4000 is humming along. The LCD works now (after the manual install of lcdproc-extra-drivers) and I customized after looking at the lcdprog man page.

You are probably correct about an odd interrupt. I am patient with the installs and do not recall seeing anything obvious. But the whole project took about 2+ hours of downloads and install-time for a new Debian Buster install. 
THANKS for this excellent tool.
